config/routes.rb
Rails.application.routes.draw do

  root 'schools#index'

  resources :schools do
    resources :classrooms
  end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
	validates_presence_of :name, :student_count

	def proportion_of_school
		student_count/School.find(school_id).student_count
	end
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :classrooms
	validates_presence_of :name, :capacity, :student_count

	def percent_full
		student_count/capacity
	end

	def school_size
		if capacity >= 4000
			"Large"
		else
			"Small"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classroom_controller.rb
class ClassroomController < ApplicationController
	before_action :school_instance
	before_action :classroom_instance, except: [:new, :index, :create]

  def index
  	@classrooms = @school.classrooms.all
  end

  def show
  end

  def new
  	@classroom = @school.classrooms.new
  end

  def create
  	@classroom = @school.classrooms.new(classroom_params)
  	if @classroom.save
  		flash[:success] = 'Classroom created'
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @classroom.update(classroom_params)
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :edit
  	end
  end

  def destroy
  	@classroom.destroy
  	redirect_to school_classroom_index_path(@school)
  end

  private

  def classroom_params
  	params.require(:classroom).permit(:name, :student_count, :subject)
  end

  def school_instance
  	@school = School.find(params[:school_id])
  end

  def classroom_instance
  	@classroom = @school.classrooms.find(params[:id])
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	before_action :school_instance
	before_action :classroom_instance, except: [:new, :index, :create]

  def index
  	@classrooms = @school.classrooms.all
  end

  def show
  end

  def new
  	@classroom = @school.classrooms.new
  end

  def create
  	@classroom = @school.classrooms.new(classroom_params)
  	if @classroom.save
  		flash[:success] = 'Classroom created'
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @classroom.update(classroom_params)
  		redirect_to school_classroom_path(@school, @classroom)
  	else
  		render :edit
  	end
  end

  def destroy
  	@classroom.destroy
  	redirect_to school_classrooms_path(@school)
  end

  private

  def classroom_params
  	params.require(:classroom).permit(:name, :student_count, :subject)
  end

  def school_instance
  	@school = School.find(params[:school_id])
  end

  def classroom_instance
  	@classroom = @school.classrooms.find(params[:id])
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :school_instance, except: [:index, :new, :create]
  def index
  	@schools = School.all
  end

  def show
  end

  def new
  	@school = School.new
  end

  def create
  	@school = School.new(school_params)
  	if @school.save
  		flash[:success] = "School created"
  		redirect_to school_path(@school)
  	else
  		flash[:danger] = @school.errors.full_messages.join('<br>').html_safe
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @school.update(school_params)
  		flash[:success] = "School updated"
  		redirect_to school_path(@school)
  	else
  		flash[:danger] = @school.errors.full_messages.join('<br>').html_safe
  		render :edit
  	end
  end

  def destroy
  	@school.destroy
  	flash[:success] = "School deleted"
  	redirect_to schools_path
  end

  private

  def school_instance
  	@school = School.find(params[:id])
  end

  def school_params
  	params.require(:school).permit(:name, :state, :capacity, :student_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for [@school, @classroom] do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name%>
	</div>
	<div>
		<%= f.label :subject %>
		<%= f.text_field :subject %>
	</div>
	<div>
		<%= f.label :student_count %>
		<%= f.number_field :student_count %>
	</div>
	<%= f.submit nil, id: 'create-classroom-btn', class: 'btn btn-primary' %>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Classroom#edit</h1>
<p>Find me in app/views/classroom/edit.html.erb</p>

app/views/classrooms/index.html.erb
<h1>Classroom#index</h1>
<p>Find me in app/views/classroom/index.html.erb</p>

app/views/classrooms/new.html.erb
<h1 class='center'>Create classroom for <%= @school.name %></h1>

<div class='row'>
	<div class='col s12 m6 offset-m3'>
		<%= render 'form' %>
	</div>
</div>

app/views/classrooms/show.html.erb
<h1 id='classroom-heading' class='center'><%= @classroom.name %></h1>

<div class='container'>
	<div>
		School: <%= link_to @school.name, school_path(@school), id: 'belongs-to-school' %>
	</div>
	<div id='subject'>
		Subject: <%= @classroom.subject %>
	</div>
	<div id='student-count'>
		Student Count: <%= @classroom.student_count %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Schoolz</a>
      <ul id="nav-mobile" class="right">
        <li><%= link_to 'All Schools', schools_path %></li>
      </ul>
    </div>
  </nav>
<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :state %>
		<%= f.text_field :state %>
	</div>

	<div>
		<%= f.label :capacity %>
		<%= f.number_field :capacity %>
	</div>

	<div>
		<%= f.label :student_count %>
		<%= f.number_field :student_count %>
	</div>

	<%= f.submit nil, id: 'create-school-btn', class: 'btn' %>
<% end %>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

app/views/schools/index.html.erb
<h1 id='schools-header' class='center'>All Schools</h1>

<div class='container'>
	<% if @schools.any? %>
		<% @schools.each do |school| %>
			<h3 id='school-title'><%= link_to school.name, school_path(school) %></h3>
		<% end %>
	<% else %>
		<h2 id='no-schools'>No schools yet :/</h2>
	<% end %>
</div>

<hr>

<div>
	<%= link_to 'Create new school', new_school_path, id: 'new-school-btn' %>
</div>

app/views/schools/new.html.erb
<h1>Schools#new</h1>
<p>Find me in app/views/schools/new.html.erb</p>

app/views/schools/show.html.erb
<h1 id='school-heading' class='center'><%= @school.name %></h1>

<div class='container'>
	<div id='state'>
		Located in <%= @school.state %>
	</div>
	<div id='capacity'>
		Capacity: <%= @school.capacity %> students
	</div>
	<div id='student-count'>
		Current number of students: <%= @school.student_count %>
	</div>
</div>

<div class='container'>
	<% if @school.classrooms.any? %>
		<h3 id='classrooms-subheading'>Classrooms</h3>
		<% @school.classrooms.each do |classroom| %>
			<div>
				<h4><%= link_to classroom.name, school_classroom_path(@school, classroom), class: 'classroom-name'%></h4>
			</div>
		<% end %>
	<% end %>
</div>

<hr>

<%= link_to 'Add classroom', new_school_classroom_path(@school), id: 'new-classroom-btn' %>